export const DEFAULT_SETTINGS = {
    backend: "claude-agent",
    systemPrompt: "You are a wiki assistant for a technical knowledge base. Be precise, factual, and concise. Use only the provided sources.",
    domains: [],
    maxTokens: 4096,
    agentLogPath: "",
    historyLimit: 20,
    timeouts: { ingest: 300, query: 300, lint: 900, init: 3600 },
    history: [],
    claudeAgent: {
        iclaudePath: "",
        model: "sonnet",
        perOperation: false,
        operations: {
            ingest: { model: "haiku", maxTokens: 4096 },
            query: { model: "sonnet", maxTokens: 4096 },
            lint: { model: "sonnet", maxTokens: 8192 },
            init: { model: "sonnet", maxTokens: 8192 },
        },
    },
    nativeAgent: {
        baseUrl: "http://localhost:11434/v1",
        apiKey: "ollama",
        model: "llama3.2",
        temperature: 0.2,
        topP: null,
        numCtx: null,
        perOperation: false,
        operations: {
            ingest: { model: "llama3.2", maxTokens: 4096, temperature: 0.2 },
            query: { model: "llama3.2", maxTokens: 4096, temperature: 0.2 },
            lint: { model: "llama3.2", maxTokens: 8192, temperature: 0.2 },
            init: { model: "llama3.2", maxTokens: 8192, temperature: 0.2 },
        },
    },
};
